"""empty message

Revision ID: c8f22b18c02b
Revises: 
Create Date: 2026-04-15 10:41:24.480805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8f22b18c02b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
